### ISSUE TITLE
Mac OS Support for this build is lacking, needs better.

### ISSUE THREAD

**Issue by Jonesx2** [sm64pc/sm64pc#519]
Hi everyone,

Im new to GitHub here, I hope everyones doing fine. 
I tried building sm64ex the OSX Build on Linux 18.04 with gcc g++ 11.0 and preinstalled gcc/g++ 7.5.0 respectively, but it didnt work. 

The problem here is this log:

cc -c -O2   -I include -I build/us_pc -I build/us_pc/include -I src -I . -DRAPI_GL=1 -DWAPI_SDL2=1 -DAAPI_SDL2=1 -DCAPI_SDL2=1 -DHAVE_SDL2=1 -I/usr/include -I/usr/include/SDL2 -D_REENTRANT -DVERSION_US -D_LANGUAGE_C -DNIGHTLY -DGIT_HASH="\"afc7e8d\"" -DNON_MATCHING -DAVOID_UB -DOSX_BUILD -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -DTEXTURE_FIX -DEXT_OPTIONS_MENU -o build/us_pc/src/pc/fs/fs.o src/pc/fs/fs.c
**In file included from levels/bbh/leveldata.c:12:0:
./levels/bbh/texture.inc.c:3:10: fatal error: levels/bbh/0.rgba16.inc.c: No such file or directory
 #include "levels/bbh/0.rgba16.inc.c"**
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1016: recipe for target 'build/us_pc/levels/bbh/leveldata.o' failed
make: *** [build/us_pc/levels/bbh/leveldata.o] Error 1
make: *** Waiting for unfinished jobs....

---------------------

I compared the folder and this texture.inc.c file to the official sm64port and it doesn't seem different, then changed the characters to png instead of inc.c thinking it just cant grab the png file in the bbh Folder (its assets like Buu Huu paintings etc.) I know there is no inc.c file for them, but why can i compile the normal sm64port but not this?

I even changed the path mentioned in the textures.inc.c file to the whole complete path etc. It didnt change. 

I added some things for make in the build too: make VERSION=us OSX_BUILD=1 WINDOWS_CONSOLE=1 TEXTURE_FIX=1 EXT_OPTIONS_MENU=1 -j4

With or without make changes, its stuck there. 

Please if anyone has a clue, help a fella out :-D

Thank you.

PS: Do I perhaps have to use the base port Version? But how? Folder etc.? How do I embed it into make??

**Comment by kewlduda** [comment]
You can build on a mac using the GNU toolchain, not so sure about linux.

`% brew install make mingw-w64 gcc sdl2 pkg-config glew glfw libusb`
`gmake OSX_BUILD=1`

This ought to be in the wiki, to be fair.
