### PR TITLE
Fix WebGL building

### LINKED ISSUE #79: Error while compiling for web.
I get an error while compiling for web, i have installed `emsdk` from AUR, but i get the following error:

`make: emcc: No such file or directory.`
`make: *** [Makefile:735: build/us_web/src/engine/behavior_script.o] Error 127`

 
- OS: Arch Linux 64-bit

### LINKED ISSUE #96: Compilation error for WebGL build
Hello, the compiler complain about "src/game/main.h" file on line 76, and want this replacement :

`extern void main(void)`

Should apparently be replaced by

`extern int main(void)`

### LINKED ISSUE #148: Make for TARGET_WEB is broken
**Describe the bug**

Edit: ~This appears to dupe #96~ The suggested fix from there doesn't work.

Attempting to build with TARGET_WEB=1 results in an error:
```
src/game/mario_actions_cutscene.c:274:17: error: implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))' [-Werror,-Wimplicit-function-declaration]
                exit(0);  // exit after saving game
                ^
src/game/mario_actions_cutscene.c:274:17: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
1 error generated.
Makefile:796: recipe for target 'build/us_web/src/game/mario_actions_cutscene.o' failed
make: *** [build/us_web/src/game/mario_actions_cutscene.o] Error 1
make: *** Waiting for unfinished jobs....
1 warning generated.
```

**To Reproduce**
```shell
make VERSION=us TARGET_WEB=1 -j4
```

**Expected behavior**
A clean build.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
The build fails in exactly the same way using the Docker container.

I ran a `git bisect` on the code to try to figure out when this problem was introduced, and came up with [this commit](https://github.com/sm64pc/sm64pc/commit/691d6f382bb3b5c3feb8f4026d3b921e2ce492c7):

```
✘-2 /opt/sm64pc [:691d6f3|BISECTING|…1] 
00:20 $ git bisect bad
691d6f382bb3b5c3feb8f4026d3b921e2ce492c7 is the first bad commit
commit 691d6f382bb3b5c3feb8f4026d3b921e2ce492c7
Author: Hyenadae <Hyenadae@github.com>
Date:   Mon May 11 06:58:33 2020 -0400

    WIP In-Game Exit via pause+save menus w/ Localizations

:040000 040000 4822f344dd9e4b0064432b03df46832a70564c9d 56853ef10793d5bf3b02dd699b1431989ec40265 M	include
:040000 040000 ae163095a105d81a44b6fab1b77040d6a9512846 f23a7c1bc8a53903b81bcfd9fec3defdf75d64d1 M	src
```

### PR DESCRIPTION
**Pull request by coltongit**
Fixes #148.
Fixes #96.
Fixes #79.

### CODE REVIEW

**Comment by RulerOf** [comment]
@coltongit Doesn't seem to work for #151 unfortunately:

```
09:01 $ git rev-parse HEAD
37f3d6a7af50caff8dceb96d34c564023d126e03
✔ /opt/sm64pc [:37f3d6a|…1] 
09:45 $ source emsdk/emsdk_env.sh; make clean; make TARGET_WEB=1 -j4
Setting environment variables:
EMSDK = /opt/sm64pc/emsdk
EM_CACHE = /opt/sm64pc/emsdk/upstream/emscripten/cache
<snip>
In file included from src/game/mario_actions_cutscene.c:31:
In file included from /opt/sm64pc/emsdk/upstream/emscripten/system/include/compat/stdlib.h:14:
/opt/sm64pc/emsdk/upstream/emscripten/system/include/libc/stdlib.h:58:10: error: expected identifier or '('
int abs (int);
         ^
/opt/sm64pc/emsdk/upstream/emscripten/system/include/libc/stdlib.h:58:10: error: expected ')'
/opt/sm64pc/emsdk/upstream/emscripten/system/include/libc/stdlib.h:58:5: note: to match this '('
int abs (int);
    ^
src/engine/math_util.h:32:17: note: expanded from macro 'abs'
#define abs(x) ((x) < 0 ? -(x) : (x))
                ^
In file included from src/game/mario_actions_cutscene.c:31:
In file included from /opt/sm64pc/emsdk/upstream/emscripten/system/include/compat/stdlib.h:14:
/opt/sm64pc/emsdk/upstream/emscripten/system/include/libc/stdlib.h:58:5: error: expected ')'
int abs (int);
    ^
src/engine/math_util.h:32:21: note: expanded from macro 'abs'
#define abs(x) ((x) < 0 ? -(x) : (x))
                    ^
/opt/sm64pc/emsdk/upstream/emscripten/system/include/libc/stdlib.h:58:5: note: to match this '('
src/engine/math_util.h:32:16: note: expanded from macro 'abs'
#define abs(x) ((x) < 0 ? -(x) : (x))
               ^
3 errors generated.
Makefile:796: recipe for target 'build/us_web/src/game/mario_actions_cutscene.o' failed
make: *** [build/us_web/src/game/mario_actions_cutscene.o] Error 1
make: *** Waiting for unfinished jobs....
```

Were you able to. build the WebGL version successfully after this patch?

**Comment by RulerOf** [comment]
@Tikilou Could you share how you prepared Emscripten? I replicated what I found in the Dockerfile on my Ubuntu system, and naturally got the same behavior in docker and Ubuntu.

**Comment by DanTheMan827** [comment]
Sound not working is due to how chrome handles the audio context, it doesn’t unlock it until you interact with the page somehow

**Comment by Tikilou** [comment]
I'm on Manjaro Linux, i'm not sure it could help you but after installed emscripted :

`sudo ln -s /usr/lib/emscripten/emcc /usr/local/bin/
sudo ln -s /usr/lib/emscripten/emcc.py /usr/local/bin/`

Then configure ~/.emscriten after first try :+1: 
Replaced 
`BINARYEN_ROOT = os.path.expanduser(os.getenv('BINARYEN', '')) # directory`

by
`BINARYEN_ROOT = os.path.expanduser(os.getenv('BINARYEN', '/usr/lib/emscripten/')) # directory`

You need to show where are emscripten in the config file.

**Comment by Tikilou** [comment]
> Sound not working is due to how chrome handles the audio context, it doesn’t unlock it until you interact with the page somehow

I understand that.

Anyway, it's not working for me on latest release of Firefox

`Loading configuration from 'sm64config.txt'
Config file 'sm64config.txt' not found. Creating it.
Saving configuration to 'sm64config.txt'
Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x2135467, but received 0xe1d350 6d`

**Comment by coltongit** [comment]
Already been fixed in PR #163.

**Comment by coltongit** [comment]
The person in issue #96 is still having issues with this even in the latest master and nightly builds, so I'll be reopening this.

**Comment by coltongit** [comment]
So Ubuntu and Majaro have different behavior when it comes to the stdlib.h from the looks of things here. Wonder how this can be addressed.

**Comment by coltongit** [comment]
@RulerOf @Tikilou @lolxnn can you all test WebGL building using the latest changes from this PR? I just pushed a fix that should fix it for all of you at once

**Comment by Tikilou** [comment]
> @RulerOf @Tikilou @lolxnn can you all test WebGL building using the latest changes from this PR? I just pushed a fix that should fix it for all of you at once
Thanks !  It's compiling and launch on PC browsers, and Android browsers devices.
But for every browsers/systems, there is a new warning  "Warning: VSync is not enabled or not working. Falling back to timer for synchronization", and sync of sound is not goodon computers. (sound stuttering)
First successfully compiled build wasn't have this problem.

Logs of Firefox console :

`wasm streaming compile failed: TypeError: Response has unsupported MIME type sm64.us.f3dex2e.html:1246:19
    printErr http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.html:1246
    instantiateAsync http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:1767
falling back to ArrayBuffer instantiation sm64.us.f3dex2e.html:1246:19
    printErr http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.html:1246
    instantiateAsync http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:1768
Loading configuration from 'sm64config.txt' sm64.us.f3dex2e.html:1237:21
Config file 'sm64config.txt' not found. Creating it. sm64.us.f3dex2e.html:1237:21
Saving configuration to 'sm64config.txt' sm64.us.f3dex2e.html:1237:21
Calling stub instead of sigaction() sm64.us.f3dex2e.html:1246:19
    printErr http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.html:1246
    _sigaction http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:8675
    SDL_QuitInit http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:1043576
    SDL_InitSubSystem http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:1001752
    SDL_Init http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:1002206
    gfx_sdl_init http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:896228
    gfx_init http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:880813
    main_func http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:870917
    main http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:871339
    _main http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:8843
    callMain http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:9335
    doRun http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:9397
    run http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:9408
Calling stub instead of sigaction() sm64.us.f3dex2e.html:1246:19
    printErr http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.html:1246
    _sigaction http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:8675
    SDL_QuitInit http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:1043612
    SDL_InitSubSystem http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:1001752
    SDL_Init http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:1002206
    gfx_sdl_init http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:896228
    gfx_init http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:880813
    main_func http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:870917
    main http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:871339
    _main http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:8843
    callMain http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:9335
    doRun http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:9397
    run http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:9408
emscripten_set_main_loop_timing: Cannot set timing mode for main loop since a main loop does not exist! Call emscripten_set_main_loop first to set one up. sm64.us.f3dex2e.js:4454:17
    _emscripten_set_main_loop_timing http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:4454
    _eglSwapInterval http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:5834
    eglSwapInterval http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:0
    SDL_EGL_SetSwapInterval http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:1444636
    SDL_GL_SetSwapInterval http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:1423920
    gfx_sdl_init http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:896365
    gfx_init http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:880813
    main_func http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:870917
    main http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js line 1749 > WebAssembly.instantiate:871339
    _main http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:8843
    callMain http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:9335
    doRun http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:9397
    run http://mywebsite.com/sm64webgl/sm64.us.f3dex2e.js:9408
Warning: VSync is not enabled or not working. Falling back to timer for synchronization`

**Comment by fgsfdsfgs** [comment]
That's fixed in the latest master, as soon as we unfuck our repo you can probably try that out.

**Comment by Tikilou** [comment]
> That's fixed in the latest master, as soon as we unfuck our repo you can probably try that out.

Okay, i've found an another bug too. Fullscreen show the game now, but the game is not streetched on the entire screen, it stay like without fullscreen. 

Capture d’écran de 2020-05-19 02-12-01

**Comment by fgsfdsfgs** [comment]
Looks like webGL doesn't like `FULLSCREEN_DESKTOP` or actually does force the window size passed to `SDL_CreateWindow` when that is used, even though it's supposed to ignore it.

**Comment by Tikilou** [comment]
> Looks like webGL doesn't like `FULLSCREEN_DESKTOP` or actually does force the window size passed to `SDL_CreateWindow` when that is used, even though it's supposed to ignore it.
> You can try master now by the way.

Master still have problems. logs :

[logs.txt](https://github.com/sm64pc/sm64pc/files/4647547/logs.txt)

**Comment by RulerOf** [comment]
@fgsfdsfgs the performance problem is gone, thanks.

@fgsfdsfgs and @Tikilou , I don't know how to change the output behavior of Emcripten, but the output behaved ideally for me after I made [these modifications](https://gist.github.com/RulerOf/1ecaccced6be88fb73a31a1dbb992452). You can replace your HTML file with this one if you like. 

Use the browser's builtin Full Screen mode.

**Comment by coltongit** [comment]
Refactored in PR #207.
